### ISSUE TITLE
GUI Screenshot?

### ISSUE THREAD

**Issue by PySimpleGUI** [garashchenko/mystic-why#1]
It's always nice to hear about a GUI being part of a Python program.  They're not all that common.  It would be great to see a screenshot of your GUI in your readme.  People like seeing pictures.

Is there a specific reason you used PySimpleGUIQt instead of the tkinter version of PySimpleGUI?

**Comment by garashchenko** [comment]
Thanks for your feedback! I will add some screenshots

I went with PySimpleGUIQt for a native system tray element. I liked the idea of the Tkinter system tray using an icon though!

**Comment by PySimpleGUI** [comment]
Ahhhhhh.... system tray!  Nice to see it being used.  I like the screenshot too.  Maybe grab a shot of your system tray too to show that you create an icon that's running down there.  GUIs are rare, a GUI with a system tray icon is even rarer.  And I saw you're extending your layout at runtime, another rare feature. Great job of making a really interesting program.

Maybe visitors would be interested in learning how you made that fancy GUI?  PySimpleGUI isn't that well-known.  It would be great to be in the list of projects at the bottom ;-)
