### ISSUE TITLE
Please add more effects

### ISSUE THREAD

**Issue by TuxedoHusky** [garashchenko/mystic-why#5]
Hi Garaschchenko!

This is super great work man! I can finally have a huewheel effect on my MSI b550 MAG tomahawk!
Thank you so much! I tried seeing if i could add effects myself and currently learning python basics but this is very much too advanced for me at the moment!

Please add more effects Garaschchenko!
Honestly I would be happy with just one effect:
Basically the same as the Rainbow effect in mystic light but I just want to be able to choose the colors, so that instead of cycling through 7 colors I could set up 2 or 3 colors. Is that possible?

**Comment by garashchenko** [comment]
Hey, thanks for your feedback. I will look into adding this effect but it will take some time cause I don't have an MSI motherboard at the moment. It might take a week or two, so stay tuned :D

**Comment by garashchenko** [comment]
Just posted a new release with this rainbow effect! Let me know if I got it right

**Comment by TuxedoHusky** [comment]
Hey Garaschenko!

This is working perfectly! Great work man!
